### ISSUE TITLE
This project is not a example of clean architecture 

### ISSUE THREAD

**Issue by urbandroid** [mp911de/CleanArchitecture#4]
![module-dependency-diagram](https://user-images.githubusercontent.com/9538233/29133216-68be044c-7d3b-11e7-9f2c-73f7930b3147.png)

As you can see dependency graph is not web -> contracts(application services) -> use cases (domain services) -> application-model(domain-model)

https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html

Either interface adapters missing or misplaced depending on your perspective.

**Comment by mp911de** [comment]
The linked 8thlight diagram explains the structural dependencies. The image from above shows runtime dependencies. Contracts (interfaces) must not depend on their implementation, otherwise, something went wrong. 
On the other side, `web` packages the application hence the runtime module must depend (inclusive transitive dependencies) on all application modules. The runtime module is also in charge of wiring all dependencies. Both aspects aren't covered by the blog post but require a manifestation in some place which is done in this case by the `web` application.

**Comment by urbandroid** [comment]
Ok. Can you map existing structure to clean architecture layers?

**Comment by mp911de** [comment]
That's already done in the readme.
